### ISSUE TITLE
Implementing "hall of fame" configurations using aff3ct as library

### ISSUE THREAD

**Issue by igorauad** [aff3ct/aff3ct#38]
Hi,

I have one other question. I'm trying to explore aff3ct as a library and particularly trying to play with the examples from the `aff3ct/my_project_with_aff3ct` repository. For instance, the example at the "examples/bootstrap/src” directory. Now, my next goal is to understand how I can validate a more complex system, like the one whose parameters are listed in the link below:

https://github.com/aff3ct/error_rate_references/blob/master/TURBO/AWGN/BPSK/RSC_RSC/BCJR/LTE/Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt

I was wondering whether there would be other examples like the one in the ""examples/bootstrap/src”” directory, but for the “hall of fame” configurations from the website, like what I believe is the above Turbo N 18444 K 6144 configuration. Would there be a repository with such examples?

Thanks again

**Comment by bonben** [comment]
Hello again Igor.

For a more flexible example of AFF3CT used as a library, take a look at :
https://github.com/aff3ct/my_project_with_aff3ct/tree/master/examples/factory

Here the parameters of your simulation can be set as program arguments, like it is done with AFF3CT used as a simulator.

Maybe it will fit your needs ?
Come back to us anytime.
Mathieu.

**Comment by igorauad** [comment]
Hello Mathieu,

Many thanks for the information. It was very useful.

I am starting to get somewhere, but not quite there yet =)

I worked a bit on this today and made the following changes in order to try Turbo codec examples:

https://github.com/igorauad/my_project_with_aff3ct/commit/16c3623e34baf569f1a028b27d7a115a0df82743

I know there is still something missing, since the BER I am getting is not correct. My next steps will be to try "loopback" simulations using each processing "layer" at a time. For example, I did a Source -> CRC adder -> CRC extractor -> Error checking. Next I will include "Encoder and Decoder" in the middle. Then puncturer and so on. Although this might not be simple given the output of the Tx side is not necessarily suitable for the input on Rx side. For example, encoder output (as far as I understand) is a stream of bits, while the soft decoder takes LLRs in its input.

I did the above changes based on inspection in the "connections" that are carried at [BFER_std_threads.cpp](https://github.com/aff3ct/aff3ct/blob/fcd41ffd04238e314b48ec5d391265e1407975a8/src/Simulation/BFER/Standard/Threads/BFER_std_threads.cpp). This source file seems a useful reference.

Anyways, if you have suggestions, please let me know.

This factory example is helpful for an initial understanding. However, I believe that I will want to try the "module" approach of the Bootstrap directory. My ultimate goal is to review the implementation adopted in the [Blockstream Satellite receiver, specifically in its `gr-blocksat` library](https://github.com/Blockstream/gr-blocksat/blob/master/lib/turbo_decoder_impl.cc#L68). For example, I want to understand whether `sub_dec` in the line I am pointing by the `gr-blocksat` link is the correct one in order to implement the the best Turbo configuration in aff3ct's hall of fame. Also, I want to make sure that this decoder instance in the Blockstream Satellite receiver uses a soft decoder, rather than hard (which is what is used at the moment), so I need to correctly change from char to float input and the like.

I am just starting on this. Many thanks for the help. Any suggestion will be very appreciated =)

**Comment by igorauad** [comment]
Hello @kouchy 

Thanks for your feedback. I am yet to come back to this thread and continue the work that I described above.

> Could you tell us your precise BER/FER reference

The BER/FER reference is the [Turbo_N18432_K6144_BCJR_i6_p08_LTE](https://github.com/aff3ct/error_rate_references/blob/master/TURBO/AWGN/BPSK/RSC_RSC/BCJR/LTE/Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt). However, the current implementation is not fully exploiting the decoder, as the constellation de-mapper that we use feeds hard decisions mapped to -1 + 1 values into the decoder, rather than LLRs. The decoder works, but the BER is not as good as we would expect.

I have recently made a quick attempt of changing the input of our decoder wrapper (where the aff3ct decoder is instantiated) to float, in order to receive float LLRs, but somehow got undefined symbol (see below) and haven't had a chance to investigate yet. The preliminary change is in [this commit](https://github.com/Blockstream/gr-blocksat/commit/c84d725e9256064fc297d3c729fef7e53ef62fa8).

```
undefined symbol: _ZN6aff3ct6module18Decoder_turbo_fastIafEC1ERKiS4_S4_RKNS0_13Interleaver_iIiEERNS0_14Decoder_SISO_iIfEESB_bNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

> the command line you used to run your code?

Unfortunately, currently there is no quick way to test the decoder, but I will provide one soon. 

The Turbo Decoder wrapper in our code is connected to a constellation de-mapper in a GNU Radio flowgraph. In order to run the whole thing, the flowgraph and dependencies need to be built as described [here](https://github.com/Blockstream/satellite#from-source). However, this is in order to run the whole receiver, which is too much for a quick test, and also receive-only, meaning no Turbo Encoder in the loop. For isolated testing of the decoder, there is another better route, whose implementation I still need to complete.

The alternative is a [Python unittest script in the gr-blocksat repository](https://github.com/Blockstream/gr-blocksat/blob/turbo_soft/python/qa_turbo_decoder.py) which can be executed on its own to test the decoder. As it is today, this Python unittest connects a Turbo Encoder to the Turbo Decoder and checks error. However, the Turbo Encoder doesn't exist in the repo anymore. So I will update this unit test such that it reads e.g. LLRs for which the decoded result we know in advance and then we check the output of the decoder. Or anything like this.

To use the unit test, one would need:

```
git clone https://github.com/Blockstream/gr-blocksat.git
cd gr-blocksat
make
cd build/
CTEST_OUTPUT_ON_FAILURE=1 make test
```

Note this will run unit tests for all blocks in the library. To leave only the Turbo Decoder tests, the others can be removed by commenting them out in [python/CMakeLists.txt](https://github.com/Blockstream/gr-blocksat/blob/master/python/CMakeLists.txt#L51).

I will get back to you once this is all better for testing.

**Comment by kouchy** [comment]
In the [Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt](https://github.com/aff3ct/error_rate_references/blob/23b0d5defd1aa88bb8c884f013b2945efe9f781e/TURBO/AWGN/BPSK/RSC_RSC/BCJR/LTE/Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt) reference we are using 6 bits from the channel:

https://github.com/aff3ct/error_rate_references/blob/23b0d5defd1aa88bb8c884f013b2945efe9f781e/TURBO/AWGN/BPSK/RSC_RSC/BCJR/LTE/Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt#L89-L92

I think this can have a non negligible impact on the decoding performance where you are using hard input (only 1 bit).

```
undefined symbol: _ZN6aff3ct6module18Decoder_turbo_fastIafEC1ERKiS4_S4_RKNS0_13Interleaver_iIiEERNS0_14Decoder_SISO_iIfEESB_bNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

This is because you are mixing `int8_t` for the bits and `float` for the LLRs in the decoder template datatypes. At this time, if the only possible combinations for bits and LLRs are:
  - `int8_t` and `int8_t`
  - `int16_t` and `int16_t`
  - `int32_t` and `float` **(I suggest you to use this combination for your tests)**
  - `int64_t` and `double`

I hope it helps.
Come back to us anytime.

**Comment by igorauad** [comment]
@kouchy fantastic! many thanks for the tip regarding the data types that need to be `int32_t` and `float`.

I have tested that today successfully. The soft decoder is working. Now I need a better way to assess performance using the python unit tests I referred to above.

I will share updates once that is done. The most up-to-date patch is now [this](https://github.com/Blockstream/gr-blocksat/commit/4c8999912e0911d0e28ec8792af9c7e024cefb71).

Btw, is there an easy way to reorder LLRs in the input to the decoder? I found that when I use QPSK, the order in which our soft decoder outputs LLRs for bits is not the same as the order that is used in the encoder side, which creates an incompatibility. In case there is any aff3ct module with an efficient implementation for such a reordering, please let me know. 

Thanks so much for your help.

**Comment by igorauad** [comment]
@kouchy , I am coming back to this task today.

I now have a GNU Radio simulation flowgraph like so:

```
Data source -> Turbo Encoder -> BPSK Symbol Mapper -> AWGN Channel -> Soft BPSK De-mapper -> Turbo Decoder
```
It is all working better than before, and I came close to the BER performance in [Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt](https://github.com/aff3ct/error_rate_references/blob/23b0d5defd1aa88bb8c884f013b2945efe9f781e/TURBO/AWGN/BPSK/RSC_RSC/BCJR/LTE/Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt). In my simulation, I am getting the following ranges (loosely speaking, those were not long experiments):

- `Es/N0 = -3.77` dB: BER on the order of `1e-2`.
- `Es/N0 = -3.67` dB: BER on the order of `1e-3`.
- `Es/N0 = -3.57` dB: BER on the order of `1e-4`.
- `Es/N0 = -3.47` dB: BER on the order of `1e-5`.

This is not exactly the same BER performance, but surely good enough. I assume there are other factors impacting, such as the precision adopted for soft decisions, so I am not overly concerned with matching performance.

However, there is one thing I still want to do. I would like to allow the decoder to stop as soon as it decodes successfully. I am controlling the maximum number of iterations of the decoder and I see that the CPU usage scales up with this maximum number even when BER is 0, so I infer the decoder is always hitting the maximum. From my understanding, this is done by using CRC, correct? Is this used in the configuration at [Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt](https://github.com/aff3ct/error_rate_references/blob/23b0d5defd1aa88bb8c884f013b2945efe9f781e/TURBO/AWGN/BPSK/RSC_RSC/BCJR/LTE/Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt)? Also, this would require injecting the CRC on encoder side, correct?

Here is a fragment of the encoder instantiation in our encoder wrapper:
```{c}
std::vector<int> poly = {013, 015};
int tail_length = (int)(2 * std::floor(std::log2((float)std::max(poly[0], poly[1]))));
int N_cw        = 2 * K + tail_length;

interleaver = new module::Interleaver_LTE<int> (K);
interleaver->init();
sub_dec = new module::Encoder_RSC_generic_sys<B_8> (K, N_cw, true, poly);
enc = new module::Encoder_turbo <B_8>(K, N, *interleaver, *sub_dec, *sub_dec);
```

Other than this, I have one more question: is it possible (or easy) to flip the convention adopted for how LLRs map to bits in the decoder? Please correct me if this question doesn't make sense at all. The soft constellation de-mapper I use adopts positive LLR to represent bit "1" and negative LLR otherwise. So at the moment I am multiplying the output of the soft de-mapper by -1 prior to feeding into the aff3ct Turbo Decoder.

**Comment by bonben** [comment]
Hi @igorauad 
First of all we are glad that you could integrate aff3ct in your project !

Concerning the stopping criterion with Turbo codes and CRC.
In aff3ct, as long as you had a CRC to the Turbo decoder, it will be used as a stopping criterion.
For example, you can add a CRC to the command in [Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt](https://github.com/aff3ct/error_rate_references/blob/23b0d5defd1aa88bb8c884f013b2945efe9f781e/TURBO/AWGN/BPSK/RSC_RSC/BCJR/LTE/Turbo_N18432_K6144_BCJR_i6_p08_LTE.txt)

`aff3ct -p "8" --sim-type "BFER" -C "TURBO" -K "6144" -e "500" -m "0.0" -M "1.01" --enc-sub-std "LTE" --dec-sub-implem "VERY_FAST" --dec-sub-simd "INTER" -i "6" --dec-sf-type "LTE_VEC" --qnt-bits "6" --qnt-dec "2" --mdm-no-sig2 --dec-sub-max "MAX" --crc-poly 24-LTEA --crc-implem INTER`

Note that as we use the INTER simd implementation in the decoder, the CRC implementation should also be INTER accordingly. However, you may note that adding a stopping criterion is not always beneficial to the throughput. The main reason, besides the overhead of CRC computation, is that with the INTER method, multiple frames are decoded simultaneously. Therefore every frame have to be stopped in order to process the next batch of frames. 

You may though observe a throughput gain if you increase the number of turbo iterations (`-i 60`). Or if you use a sequential implementation of the decoder : 
`./bin/aff3ct -p "8" --sim-type "BFER" -C "TURBO" -K "6144" -e "500" -m "1.0" -M "1.01" --enc-sub-std "LTE" --dec-sub-implem "FAST" -i "6" --dec-sf-type "LTE_VEC" --qnt-bits "6" --qnt-dec "2" --mdm-no-sig2 --dec-sub-max "MAX"  -t 1  --sim-stats`
vs
`./bin/aff3ct -p "8" --sim-type "BFER" -C "TURBO" -K "6144" -e "500" -m "1.0" -M "1.01" --enc-sub-std "LTE" --dec-sub-implem "FAST" -i "6" --dec-sf-type "LTE_VEC" --qnt-bits "6" --qnt-dec "2" --mdm-no-sig2 --dec-sub-max "MAX" --crc-poly 24-LTEA --crc-implem FAST -t 1  --sim-stats`

Note also that you can select the starting CRC checking iteration with the following argument : [--dec-crc-start](https://aff3ct.readthedocs.io/en/latest/user/simulation/parameters/codec/turbo/decoder.html#dec-crc-start)

Nevertheless, should you want to add CRC stopping criterion to your decoder in your project, you will find the way to do it here in the Turbo codec implementation : 
https://github.com/aff3ct/aff3ct/blob/master/src/Module/Codec/Turbo/Codec_turbo.cpp#L133-L154

Don't hesitate to ask if further help is needed :wink:
