### ISSUE TITLE
"mipp::mul<int32_t> (SSE2) is undefined!" when using --src-implem "FAST"` with LDPC for database examples

### ISSUE THREAD

**Issue by adomasbaliuka** [aff3ct/aff3ct#75]
I am simulating DVB-S2 LDPC on a BSC by running the command 
`aff3ct --sim-type "BFER" -C "LDPC" --src-type "RAND" --src-implem "FAST" --enc-type "LDPC_DVBS2" -K "10800" -N "16200" -e "100" --dec-type "BP_HORIZONTAL_LAYERED" --dec-implem "NMS" -i "30" --dec-norm "0.825" --dec-simd "INTER" --chn-type "BSC" --mdm-type "OOK" -R "0.1:0.05:0.5,0.01:0.002:0.1" -E "EP"` 
The command is taken from an [example in the AFF3CT database](https://aff3ct.github.io/comparator.html?curve0=ab07ec2&xaxis=EP&yaxes=BER%2CFER). I tried to do this with master branch and development branch, getting the same error both times. 

The issue lies with the option `--src-implem "FAST"`. **When this option is not used, the simulation works with both branches and reproduces the database results.** The database website claims that the commands listed should work on the development branch. The documentation does not warn about possible issues with `--src-implem "FAST"`.

 The exact commits I used were:
 1. master branch, commit  1ceddfc874f38317e83592b506b1fe78dffe44b4 with submodules
 ccc3111fba49e48fca67a19caf347148e1139ddf conf (heads/master)
 de5238dec3fc64448c5e99ea522e5c2c786dc4de lib/MIPP (de5238d)
 e5c69d84ab5db3e06170b8eedec1d87841c7fb22 lib/date (v2.4.1-5-ge5c69d8)
 49505595c6941ad58788ade0ecdff26aeb5b7a9a lib/rang (v3.1.0)
 1d8ba69eae32f73923b025de175f6bd4392ac9e9 refs (heads/master)
leading to [master_output.txt](https://github.com/aff3ct/aff3ct/files/4917360/master_output.txt)

 2.  development branch, commit 4fdaa13fda1e7909c1fb768f9a4e8323c287eec7 with submodules
 9d7257598885dc49b950b963893f86fa710f3104 conf (remotes/origin/development)
 257979855f4620416a7ec8230f5124e38090db9c lib/MIPP (heads/master)
 2bc647e09fef5c7321e4854f6f6d3d7c39642102 lib/cli (2bc647e)
 e5c69d84ab5db3e06170b8eedec1d87841c7fb22 lib/date (v2.4.1-5-ge5c69d8)
 49505595c6941ad58788ade0ecdff26aeb5b7a9a lib/rang (v3.1.0)
 c75c99b207fabb93337e63221085c2a1595d56f3 refs (remotes/origin/development)
leading to [output.txt](https://github.com/aff3ct/aff3ct/files/4917340/output.txt).

**Comment by kouchy** [comment]
Hi @adomasbaliuka,

The problem comes from your AFF3CT compilation options. Generally the `FAST` implementations are relying on the SIMD instructions that are wrapped through the [MIPP](https://github.com/aff3ct/MIPP) library. If you don't tell your compiler to compile with your native CPU architecture, it will compile a binary with the SSE2 instructions set (which is very old). This will result in missing assembly instructions and will lead to an error like the `mipp::mul<int32_t> (SSE2) is undefined!` error.

 I suggest you to check [this documentation page](https://aff3ct.readthedocs.io/en/latest/user/installation/compilation/compilation.html#specific-options), you need to add the `-march=native` compiler option.

I hope it helps.
