### ISSUE TITLE
Question about the throughput performance of Polar Code decoder based on AVX-512 and AVX2 instruction set.

### ISSUE THREAD

**Issue by HongweiHou** [aff3ct/aff3ct#78]
First of all, thanks for your contributions to the efficient software implementation of Polar Code decoder. I hava a question about the throughput performance of Polar Code Decoder based on AVX-512 and AVX2 instruction set. Why is the throughput performance based on the AVX-512 instruction set lower than that based on the AVX2 instruction set?

I think there are two possible reasons: 
1. Since the Polar Code decoder is based on the SC/SCL algorithm, which is a type of serial algorithm, increasing the SIMD register width is not beneficial to the improvement of throughput performance, and may even decrease the throughput performance due to reasons such as cache or memory I/O.
2. The Aff3ct library only optimized for the SSE and AVX2 instruction sets, but not the AVX-512 instruction set.

Can you tell me which reason is right? Or are there other reasons? I am very interested in it.

With thanks and best regards.

**Comment by kouchy** [comment]
Hi @HongweiHou,

Sorry for the latency of the answer.

AFF3CT natively supports AVX-512 instructions set but you are right (reason 1), if you are using SIMD intra-frame decoders, having long SIMD registers is not very interesting because of the sequential parts of the decoder. In general, the proposed decoders will fall back in sequential mode if the number of elements to process is lower than the number of elements in the SIMD registers. As a consequence, in the proposed implementations, there is more sequential parts in AVX-512 than in AVX. The proposed implementation could be improve by using AVX instructions or padding technique when the number of elements can't fully fill the AVX-512 registers. However, for very long codes, AVX-512 instructions should be more efficient than AVX or SSE.

I hope it helps.
